name: Build MeoMods (1.12.2)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '8'

      - name: Ensure Gradle 4.9 (download)
        shell: pwsh
        run: |
          Set-Location ${{ github.workspace }}
          $toolsDir = Join-Path ${{ github.workspace }} 'tools'
          $gradleDir = Join-Path $toolsDir 'gradle'
          if (-Not (Test-Path $gradleDir)) {
            Write-Host "tools\gradle not found — downloading Gradle 4.9"
            $zip = "gradle-4.9-bin.zip"
            try {
              Invoke-WebRequest -Uri 'https://services.gradle.org/distributions/gradle-4.9-bin.zip' -OutFile $zip -UseBasicParsing -ErrorAction Stop
              Expand-Archive -LiteralPath $zip -DestinationPath $toolsDir -Force
              $extracted = Join-Path $toolsDir 'gradle-4.9'
              if (Test-Path $extracted) {
                if (Test-Path $gradleDir) {
                  Write-Host "Destination $gradleDir appeared during extraction; removing extracted folder"
                  Remove-Item -Recurse -Force $extracted
                } else {
                  Move-Item -Path $extracted -Destination $gradleDir -ErrorAction Stop
                }
              } else {
                Write-Host "Warning: expected extracted folder $extracted not found"
              }
            } catch {
              Write-Host "Failed to download or extract Gradle: $($_.Exception.Message)" -ForegroundColor Yellow
              if (Test-Path $zip) { Remove-Item $zip -Force }
              throw
            } finally {
              if (Test-Path $zip) { Remove-Item $zip -Force }
            }
          } else {
            Write-Host "tools\gradle already exists — skipping download"
          }

      - name: Run build script (Local Gradle)
        shell: pwsh
        run: |
          Set-Location ${{ github.workspace }}
          powershell -NoProfile -ExecutionPolicy Bypass -File .\scripts\build-all.ps1 -Local -Version 1.12.2

      - name: Collect JARs
        shell: pwsh
        run: |
          Set-Location ${{ github.workspace }}
          powershell -NoProfile -ExecutionPolicy Bypass -File .\scripts\collect-jars.ps1 -Version 1.12.2

      - name: Generate releases manifest (JSON)
        shell: pwsh
        run: |
          Set-Location ${{ github.workspace }}
          powershell -NoProfile -ExecutionPolicy Bypass -File .\scripts\list-releases.ps1 -Version 1.12.2 -OutFormat json

      - name: Upload manifest as artifact
        uses: actions/upload-artifact@v4
        with:
          name: meomods-manifest-1.12.2
          path: releases/manifest-*.json
          retention-days: 90

      - name: Upload releases as artifact
        uses: actions/upload-artifact@v4
        with:
          name: meomods-releases-1.12.2
          path: releases
          retention-days: 90

      - name: Smoke-test: verify JAR integrity
        shell: pwsh
        run: |
          Set-Location ${{ github.workspace }}
          $releases = Join-Path ${{ github.workspace }} 'releases'
          if (-Not (Test-Path $releases)) {
            Write-Host "No releases directory found at $releases"; exit 1
          }
          Add-Type -AssemblyName System.IO.Compression.FileSystem
          $failed = $false
          Get-ChildItem -Path $releases -Filter '*.jar' -File | ForEach-Object {
            try {
              $zip = [System.IO.Compression.ZipFile]::OpenRead($_.FullName)
              # quick checks: ensure there is at least one entry and optionally mcmod.info
              if ($zip.Entries.Count -le 0) { throw "empty jar" }
              $hasMeta = $zip.Entries | Where-Object { $_.FullName -match 'mcmod.info|pack.mcmeta' }
              if (-Not $hasMeta) { Write-Host "Warning: no mcmod.info or pack.mcmeta in $($_.Name)" }
              $zip.Dispose()
              Write-Host "OK: $($_.Name)"
            } catch {
              Write-Host "INVALID JAR: $($_.Name) - $($_.Exception.Message)" -ForegroundColor Red
              $failed = $true
            }
          }
          if ($failed) { throw "One or more JARs failed integrity check" }
